title: Kong's Homepage
page-top-title: Shun Kong Cheung
top-section-bg-text: MPhil in Electronic and Computer Engineering
home-subtitle: Kong
copyright-text: '&copy; Shun Kong Cheung 2023-2024. All Rights Reserved.'
